/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuUtama.java
 *
 * Created on Mar 12, 2015, 12:23:04 AM
 */

package pos;

/**
 *
 * @author User
 */
public class MenuUtama extends javax.swing.JFrame {

    /** Creates new form MenuUtama */
    public MenuUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new panelMakeOver.backgroundPanel();
        jPanel1 = new javax.swing.JPanel();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jLabel1 = new javax.swing.JLabel();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink9 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink10 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink11 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink12 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jLabel2 = new javax.swing.JLabel();
        jXHyperlink3 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink4 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jLabel3 = new javax.swing.JLabel();
        jXHyperlink5 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink6 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane4 = new org.jdesktop.swingx.JXTaskPane();
        jLabel7 = new javax.swing.JLabel();
        jXHyperlink7 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink8 = new org.jdesktop.swingx.JXHyperlink();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jXTaskPane1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("::Modul Laporan");
        jXTaskPane1.add(jLabel1);

        jXHyperlink1.setText("Laporan Penjualan Per Periode");
        jXHyperlink1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink1.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });
        jXTaskPane1.add(jXHyperlink1);

        jXHyperlink2.setText("Laporan Pembelian Per Periode");
        jXHyperlink2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink2.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink2ActionPerformed(evt);
            }
        });
        jXTaskPane1.add(jXHyperlink2);

        jXHyperlink9.setText("Laporan Inventory");
        jXHyperlink9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink9.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink9ActionPerformed(evt);
            }
        });
        jXTaskPane1.add(jXHyperlink9);

        jXHyperlink10.setText("Laporan Data Pelanggan");
        jXHyperlink10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink10.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink10ActionPerformed(evt);
            }
        });
        jXTaskPane1.add(jXHyperlink10);

        jXHyperlink11.setText("Laporan Pendapatan Kotor");
        jXHyperlink11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink11.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink11ActionPerformed(evt);
            }
        });
        jXTaskPane1.add(jXHyperlink11);

        jXHyperlink12.setText("Laporan Pendapatan Bersih dan Pengeluaran");
        jXHyperlink12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink12.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink12ActionPerformed(evt);
            }
        });
        jXTaskPane1.add(jXHyperlink12);

        jXTaskPane2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("::Modul Utility");
        jXTaskPane2.add(jLabel2);

        jXHyperlink3.setText("Modul Import Database From Ms. Excell (tb_barang)");
        jXHyperlink3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink3.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink3ActionPerformed(evt);
            }
        });
        jXTaskPane2.add(jXHyperlink3);

        jXHyperlink4.setText("Modul Setting Password");
        jXHyperlink4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink4.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink4ActionPerformed(evt);
            }
        });
        jXTaskPane2.add(jXHyperlink4);

        jXTaskPane3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("::Modul Transaksi");
        jXTaskPane3.add(jLabel3);

        jXHyperlink5.setText("Modul Penjualan");
        jXHyperlink5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink5.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink5ActionPerformed(evt);
            }
        });
        jXTaskPane3.add(jXHyperlink5);

        jXHyperlink6.setText("Modul Pembelian");
        jXHyperlink6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink6.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink6ActionPerformed(evt);
            }
        });
        jXTaskPane3.add(jXHyperlink6);

        jXTaskPane4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("::Modul Master Data");
        jXTaskPane4.add(jLabel7);

        jXHyperlink7.setText("Modul Input Barang");
        jXHyperlink7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink7.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink7ActionPerformed(evt);
            }
        });
        jXTaskPane4.add(jXHyperlink7);

        jXHyperlink8.setText("Modul Input Pelanggan");
        jXHyperlink8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jXHyperlink8.setFont(new java.awt.Font("Tahoma", 0, 13));
        jXHyperlink8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink8ActionPerformed(evt);
            }
        });
        jXTaskPane4.add(jXHyperlink8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXTaskPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jXTaskPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTaskPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jXTaskPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jXTaskPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXTaskPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 30));
        jLabel4.setText("Point of Sale GM Helmet");

        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 80));
        jLabel5.setText("POS GM");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GM_LOGONYA.png"))); // NOI18N

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(459, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink2ActionPerformed
        // TODO add your handling code here:
        new mod_laporan_pembelian(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink2ActionPerformed

    private void jXHyperlink4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink4ActionPerformed
        // TODO add your handling code here:
        new mod_set_pass(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink4ActionPerformed

    private void jXHyperlink6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink6ActionPerformed
        // TODO add your handling code here:
        new mod_pembelian(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink6ActionPerformed

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        // TODO add your handling code here:
        new mod_laporan_penjualan(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void jXHyperlink5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink5ActionPerformed
        // TODO add your handling code here:
       new mod_penjualan(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink5ActionPerformed

    private void jXHyperlink7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink7ActionPerformed
        // TODO add your handling code here:
        new mod_input_produk(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink7ActionPerformed

    private void jXHyperlink8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink8ActionPerformed
        // TODO add your handling code here:
        new mod_input_pelanggan(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink8ActionPerformed

    private void jXHyperlink9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXHyperlink9ActionPerformed

    private void jXHyperlink10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXHyperlink10ActionPerformed

    private void jXHyperlink3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink3ActionPerformed
        // TODO add your handling code here:
        new FrameBrowse().setVisible(true);
    }//GEN-LAST:event_jXHyperlink3ActionPerformed

    private void jXHyperlink11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink11ActionPerformed
        // TODO add your handling code here:
        new mod_laporan_pendapatan_kotor(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink11ActionPerformed

    private void jXHyperlink12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink12ActionPerformed
        // TODO add your handling code here:
        new mod_laporan_untung_bersih(this, true).setVisible(true);
    }//GEN-LAST:event_jXHyperlink12ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panelMakeOver.backgroundPanel backgroundPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink10;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink11;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink12;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink4;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink5;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink6;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink7;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink8;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink9;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane4;
    // End of variables declaration//GEN-END:variables

}
