/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mod_untungbersih.java
 *
 * Created on Apr 26, 2015, 10:33:49 AM
 */

package pos;
import entitas.manager;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import org.freixas.jcalendar.JCalendarCombo;
import java.awt.EventQueue;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Julian Christian
 */
public class mod_untungbersih extends javax.swing.JDialog {
Connection con = null;
Statement sta = null;
String utgktr, utgbsh, pengeluaran;

    /** Creates new form mod_untungbersih */
    public mod_untungbersih(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/db_pos","root","");
            sta=con.createStatement();
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
     }
        //sissa();
        this.setLocationRelativeTo(null);
    }

void sissa(){
        try{
            sta=con.createStatement();
            String SQL="SELECT ROUND(SUM(tb_detail_penjualan.sub_total - (tb_barang.harga_produk * tb_detail_penjualan.kuantitas))) AS untung_kotor FROM tb_detail_penjualan "
                    + "INNER JOIN tb_barang ON tb_detail_penjualan.id_produk = tb_barang.id_produk "
                    + "INNER JOIN tb_penjualan ON tb_detail_penjualan.id_penjualan = tb_penjualan.id_penjualan "
                    + "WHERE DATE_FORMAT( tb_detail_penjualan.Tanggal,  '%m' ) = '"+cbbln.getSelectedItem().toString()+"' "
                    + "AND DATE_FORMAT ( tb_detail_penjualan.Tanggal, '20%y' ) = '"+txttahun.getText()+"'";
            ResultSet res=sta.executeQuery(SQL);
            while(res.next()){
                utgktr = res.getString("untung_kotor");
                txtkotor.setText(utgktr);
            }
            res.close();
            //sta.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
            exc.printStackTrace();
        }
    }

void pengeluaran(){
        try{
            sta=con.createStatement();
            String SQL="SELECT SUM(tb_pengeluaran.Pengeluaran) AS total_pengeluaran FROM tb_pengeluaran WHERE DATE_FORMAT( tb_pengeluaran.Tanggal,  '%m' ) =  '"+cbbln.getSelectedItem().toString()+"'"
                    + "AND DATE_FORMAT (tb_pengeluaran.Tanggal, '20%y' ) = '"+txttahun.getText()+"'";
            ResultSet res=sta.executeQuery(SQL);
            while(res.next()){
                pengeluaran = res.getString("total_pengeluaran");
                txtkeluar.setText(pengeluaran);
            }
            res.close();
            //sta.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
            exc.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        headernya1 = new panelMakeOver.headernya();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtkotor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttot = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtkeluar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txttahun = new javax.swing.JTextField();
        cbbln = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headernya1.setName("headernya1"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 23));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("POS GM");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modul Untung Bersih");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout headernya1Layout = new javax.swing.GroupLayout(headernya1);
        headernya1.setLayout(headernya1Layout);
        headernya1Layout.setHorizontalGroup(
            headernya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headernya1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headernya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(364, Short.MAX_VALUE))
        );
        headernya1Layout.setVerticalGroup(
            headernya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headernya1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setText("Untung Kotor");
        jLabel1.setName("jLabel1"); // NOI18N

        txtkotor.setEditable(false);
        txtkotor.setName("txtkotor"); // NOI18N

        jLabel2.setText("Bulan");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Untung Bersih");
        jLabel3.setName("jLabel3"); // NOI18N

        txttot.setEditable(false);
        txttot.setName("txttot"); // NOI18N

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText("SAVE");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Pengeluaran");
        jLabel7.setName("jLabel7"); // NOI18N

        txtkeluar.setEditable(false);
        txtkeluar.setName("txtkeluar"); // NOI18N
        txtkeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkeluarKeyPressed(evt);
            }
        });

        jButton3.setText("PRINT");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tahun");
        jLabel6.setName("jLabel6"); // NOI18N

        txttahun.setName("txttahun"); // NOI18N
        txttahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttahunKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttahunKeyReleased(evt);
            }
        });

        cbbln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbbln.setName("cbbln"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headernya1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbln, 0, 186, Short.MAX_VALUE)
                    .addComponent(txttahun, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtkotor, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txttot, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(283, 283, 283))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headernya1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkeluarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            
        }
    }//GEN-LAST:event_txtkeluarKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
            sta=con.createStatement();
            String SQL="SELECT * FROM tb_keuntungan WHERE tb_keuntungan.Bulan = '"+cbbln.getSelectedItem().toString()+"'";
            ResultSet res=sta.executeQuery(SQL);
            if(res.next()){
                String del = "DELETE FROM tb_keuntungan WHERE tb_keuntungan.Bulan ='"+cbbln.getSelectedItem().toString()+"'";
                sta = con.createStatement();
                int A = sta.executeUpdate(del);
                JOptionPane.showMessageDialog(rootPane, "Berhasil Hapus Data Lama");

                jual.setPengeluaran(cbbln.getSelectedItem().toString());
                jual.setUtgktr(txtkotor.getText());
                jual.setUtgbrs(txttot.getText());
                jual.setTahun(txttahun.getText());
                ma.simpanKeuntungan(jual);
            }else{
                jual.setPengeluaran(cbbln.getSelectedItem().toString());
                jual.setUtgktr(txtkotor.getText());
                jual.setUtgbrs(txttot.getText());
                jual.setTahun(txttahun.getText());
                ma.simpanKeuntungan(jual);
           }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //new mod_laporan_untung_bersih(this, true).setVisible(true);
        this.dispose();
        new mod_laporan_untung_bersih(null, true).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttahunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttahunKeyPressed
        // TODO add your handling code here:
            if(evt.getKeyCode()==10){
            sissa();
            pengeluaran();

            Integer pengluar = Integer.parseInt(txtkeluar.getText());
            Integer kotor = Integer.parseInt(txtkotor.getText());

            int hasil = (kotor) - pengluar;
            txttot.setText(Integer.toString(hasil));
        }
    }//GEN-LAST:event_txttahunKeyPressed

    private void txttahunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttahunKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttahunKeyReleased

    manager ma = new manager();
entitas.entitas_untungbersih jual = new entitas.entitas_untungbersih();
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mod_untungbersih dialog = new mod_untungbersih(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbln;
    private panelMakeOver.headernya headernya1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtkeluar;
    private javax.swing.JTextField txtkotor;
    private javax.swing.JTextField txttahun;
    private javax.swing.JTextField txttot;
    // End of variables declaration//GEN-END:variables

}
