/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mod_management_menu.java
 *
 * Created on Mar 23, 2015, 4:30:11 PM
 */

package pos;

import entitas.manager;

/**
 *
 * @author User
 */
public class mod_management_menu extends javax.swing.JDialog {
String Modul_Input_Barang,Modul_Input_Pelanggan,
        Modul_Penjualan,Modul_Pembelian,Laporan_Penjualan_Per_Periode,
        Laporan_Pembelian_Per_Periode,Laporan_Invetory,Laporan_Data_Pelanggan,
        Modul_Import_Database_From_Ms_Excell,Modul_Setting_Password;
    /** Creates new form mod_management_menu */
    public mod_management_menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headernya1 = new panelMakeOver.headernya();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMdBarang = new javax.swing.JCheckBox();
        cbMdPelanggan = new javax.swing.JCheckBox();
        cbmdPenjualan = new javax.swing.JCheckBox();
        cbMdPembelian = new javax.swing.JCheckBox();
        cbMdLpPenjualan = new javax.swing.JCheckBox();
        cbMdLpPembelian = new javax.swing.JCheckBox();
        cbMdImportDatabase = new javax.swing.JCheckBox();
        cbMdSettPass = new javax.swing.JCheckBox();
        cbLpInventory = new javax.swing.JCheckBox();
        cbMdLpPelanggan = new javax.swing.JCheckBox();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headernya1.setName("headernya1"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 23));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("POS GM");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modul Management Menu Aplikasi");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout headernya1Layout = new javax.swing.GroupLayout(headernya1);
        headernya1.setLayout(headernya1Layout);
        headernya1Layout.setHorizontalGroup(
            headernya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headernya1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headernya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        headernya1Layout.setVerticalGroup(
            headernya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headernya1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbMdBarang.setText("Modul Input Barang");
        cbMdBarang.setName("cbMdBarang"); // NOI18N

        cbMdPelanggan.setText("Modul Input Pelanggan");
        cbMdPelanggan.setName("cbMdPelanggan"); // NOI18N

        cbmdPenjualan.setText("Modul Penjualan");
        cbmdPenjualan.setName("cbmdPenjualan"); // NOI18N

        cbMdPembelian.setText("Modul Pembelian");
        cbMdPembelian.setName("cbMdPembelian"); // NOI18N

        cbMdLpPenjualan.setText("Laporan Penjualan Per Periode");
        cbMdLpPenjualan.setName("cbMdLpPenjualan"); // NOI18N

        cbMdLpPembelian.setText("Laporan Pembelian Per Periode");
        cbMdLpPembelian.setName("cbMdLpPembelian"); // NOI18N

        cbMdImportDatabase.setText("Modul Import Database From Ms. Excell (tb_barang)");
        cbMdImportDatabase.setName("cbMdImportDatabase"); // NOI18N

        cbMdSettPass.setText("Modul Setting Password");
        cbMdSettPass.setName("cbMdSettPass"); // NOI18N

        cbLpInventory.setText("Laporan Invetory");
        cbLpInventory.setName("cbLpInventory"); // NOI18N

        cbMdLpPelanggan.setText("Laporan Data Pelanggan");
        cbMdLpPelanggan.setName("cbMdLpPelanggan"); // NOI18N

        txtPass.setName("txtPass"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Password");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("KUNCI MENU");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("BUKA MENU");
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headernya1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMdBarang)
                                    .addComponent(cbMdPelanggan)
                                    .addComponent(cbmdPenjualan)
                                    .addComponent(cbMdPembelian)
                                    .addComponent(cbMdLpPenjualan))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMdLpPembelian)
                                    .addComponent(cbLpInventory)
                                    .addComponent(cbMdLpPelanggan)
                                    .addComponent(cbMdImportDatabase)
                                    .addComponent(cbMdSettPass)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headernya1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMdBarang)
                        .addGap(18, 18, 18)
                        .addComponent(cbMdPelanggan)
                        .addGap(18, 18, 18)
                        .addComponent(cbmdPenjualan)
                        .addGap(18, 18, 18)
                        .addComponent(cbMdPembelian)
                        .addGap(18, 18, 18)
                        .addComponent(cbMdLpPenjualan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMdLpPembelian)
                        .addGap(18, 18, 18)
                        .addComponent(cbLpInventory)
                        .addGap(18, 18, 18)
                        .addComponent(cbMdLpPelanggan)
                        .addGap(18, 18, 18)
                        .addComponent(cbMdImportDatabase)
                        .addGap(18, 18, 18)
                        .addComponent(cbMdSettPass)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(cbMdBarang.isSelected()==true){

        }
    }//GEN-LAST:event_jButton1ActionPerformed
manager ma = new manager();
entitas.entitas_manage_menu manag = new entitas.entitas_manage_menu();
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mod_management_menu dialog = new mod_management_menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbLpInventory;
    private javax.swing.JCheckBox cbMdBarang;
    private javax.swing.JCheckBox cbMdImportDatabase;
    private javax.swing.JCheckBox cbMdLpPelanggan;
    private javax.swing.JCheckBox cbMdLpPembelian;
    private javax.swing.JCheckBox cbMdLpPenjualan;
    private javax.swing.JCheckBox cbMdPelanggan;
    private javax.swing.JCheckBox cbMdPembelian;
    private javax.swing.JCheckBox cbMdSettPass;
    private javax.swing.JCheckBox cbmdPenjualan;
    private panelMakeOver.headernya headernya1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

}
